---
title: "README.md"
author: "Younghoon Seo"
date: "4/11/2021"
output: html_document
---

## Coursera Getting and Cleaning Data Week 4 Project Overview

The purpose of this project was to demonstrate the ability to collect, work with, and clean a data set. The goal was to prepare tidy data that can be utilized for future analysis. I had to prepare the following for the completion of this project: 1) a tidy data set, 2) a link (run_analysis.R) to a Github repository with the script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that I performed to clean up the data called CodeBook.md. I also included a README.md in the repo with the scripts to explain how all of the scripts work and how they are connected.

**Nature of the Project and Source of the Data**

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

Here are the data for the project:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip  

**Tasks**

- Merge the training and the test sets to create one data set

- Extract only the measurements on the mean and standard deviation for each measurement

- Use descriptive activity names to name the activities in the data set__

- Appropriately label the data set with descriptive variable names__

- From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject

**Files**
CodeBook.md provides information on the variables, data, and any transformations or work that I performed to clean up the data

run_analysis.R includes the code for the R script to clean up the data

tidydata.txt is the output from the run_analysis.R script
